### ISSUE TITLE
Give an option not to use eldoc.

### ISSUE THREAD

**Issue by gperaza** [et2010/org-edit-latex#11]
org-eldoc is not found in the org-mode version included in emacs. This results in the annoying message 
eldoc error: (void-function org-eldoc-documentation-function)

It would be nice to include an option to disable calls to eldoc or at least list org-eldoc as a requirement.

Thanks.

**Comment by et2010** [comment]
Thanks for the report. I've pushed a fix, please test!

**Comment by et2010** [comment]
If you still don't want the eldoc message, you can turn it off by set `org-edit-latex-show-hint` to nil

**Comment by gperaza** [comment]
Thanks, org-edit-latex-show-hint fixed it.
