### ISSUE TITLE
Wrapping issues with named blocks

### ISSUE THREAD

**Issue by joafigue** [et2010/org-edit-latex#4]
Hi,
 I found a small issue with the environment detection and wrapping when dealing with named blocks, unfortunately My lisp skills are not good enough to fix it

[org_edit_latex_before.txt](https://github.com/et2010/org-edit-latex/files/872911/org_edit_latex_before.txt)
[org_edit_latex_after.txt](https://github.com/et2010/org-edit-latex/files/872912/org_edit_latex_after.txt)

I've attached some test files I made when I discovered the issue. Basically it only appears when a special latex environment is preceded by a `#+name:`, but no other org-special command seemed to be affected by it
As shown on the "after" file, the block is not properly escaped and either the `#+name` line is modified or the document is left in an invalid.

Still Kudos for the package which became an instant part of my setup

**Comment by et2010** [comment]
Thanks for the report, I'll look into it.

**Comment by et2010** [comment]
Fixed! Thanks for the detailed report. It helped a lot during fixing this issue. The fix should work on all the cases you provided. But since it's an ad-hoc fix, there may be other use cases I'm not aware of. So feel free to reopen it if you bump into a similar issue.

It will be on MELPA soon.
