### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by wigust** [et2010/org-edit-latex#8]
Hi,

could you provide a release tarball, please? That would simplify packaging for guixsd.
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=27497

**Comment by tumashu** [comment]
Just add a tag, for example: 0.1.0 or v0.1.0 and  git push --tags

**Comment by tumashu** [comment]
https://github.com/et2010/org-edit-latex/archive/v0.8.0.tar.gz

**Comment by et2010** [comment]
@wigust @tumashu Thanks for the feedbacks! I've added a release tag.
