### ISSUE TITLE
Parse `#+LaTeX-CLASS` for styles

### ISSUE THREAD

**Issue by fleimgruber** [et2010/org-edit-latex#9]
After reading https://github.com/jkitchin/scimax/issues/117 I tried to use `TeX-insert-macro` in an `org-edit-special`.

I did not get any `\si`, `\SI` or related completion options.

It seems that org-edit-latex only parses the `#+LATEX_HEADER:` fields for e.g. `\usepackage{siunitx}` to determine which AUCTeX styles to load (by way of the generated TeX master file I assume).  With this field explicitly set, the siunitx style is availabe in the `org-edit-special`.  I use siunitx quite a bit and thus I placed the `\usepackage{siunitx}` into the class referenced by `#+LaTeX_CLASS:`.

Now the actual feature request: Parse the class set in `#+LaTeX_CLASS:` for `\usepackage{siunitx}` declarations (or use org-mode internal machinery to get those declarations) to add them to TeX master file generated by org-edit-latex.

**Comment by et2010** [comment]
Sorry, but I don't know how to achieve that.

Do you use latex preview feature from org? If so, I think a more reasonable solution is to remove `\usepackage{siunitx}` line form your class definition, and add it to `org-latex-packages-alist`:

```elisp
(add-to-list 'org-latex-packages-alist '("range-phrase=-,range-units=single" "siunitx"))
```
From docstring of `org-latex-packages-alist`, we have:

> Alist of packages to be inserted in every LaTeX header.
> ...
> Make sure that you only list packages here which:
> 
>   - you want in every file;
>   - do not conflict with the setup in ‘org-format-latex-header’;
>   - do not conflict with the default packages in
>     ‘org-latex-default-packages-alist’.
> ...

So it will appear in every LaTeX header no matter what class you choose. By this approach, you can also preview siunitx macros both in org and edit buffer.

As for your class definition, make sure it contains this line:
`[PACKAGES]`
not this:
`[NO-PACKAGES]`
or you won't have packages from `org-latex-packages-alist` in your exported TeX file.

**Comment by fleimgruber** [comment]
Thanks for the pointer.  Yes, this is indeed the way to go here, since siunitx features in most of my class definitions anyway.  Heavy LaTeX preview user as well. Thanks also for the `[PACKAGES]` hint which would have tripped me up...

**Comment by fleimgruber** [comment]
This does not seem to work anymore, there is also no mention of any of the `org-latex-packages-alist` in `TeX-active-styles` when inside the `org-edit-special` buffer. A manual `(TeX-run-style-hooks "siunitx")` loads a bunch of them that previously were not in the active styles (only `"LATEX"` was). Any ideas?

**Comment by et2010** [comment]
Thanks for the report. I'll look into this when I have some free time.

**Comment by fleimgruber** [comment]
I had a look into `org-edit-latex--create-master` and experimented a bit with it. Turns out I had an invalid frag-master.tex around. AFAICS, this file gets created when the minor mode is activated. If `org-latex-packages-alist` is modified afterwards, then this file is not recreated. I think this was the issue here. Anyways, solved for me.
